Added TestRunId

diff --git a/.github/workflows/sample-app-web.yml b/.github/workflows/sample-app-web.yml
--- a/.github/workflows/sample-app-web.yml
+++ b/.github/workflows/sample-app-web.yml
@@ -1,5 +1,3 @@
-name: Capture Visual Snapshots with Meticulous
-
 on:
   push:
     branches:
@@ -56,28 +54,23 @@ jobs:
 
       - name: Start server in background
         run: |
-          yarn add serve
-          nohup npx serve -s build -l 3000 & echo $! > server.pid
+          yarn global add serve
+          serve -s build -l 3000 & echo $! > server.pid
 
       - name: Wait for server to be ready
         run: |
           for i in {1..12}; do  
-            if curl --silent --fail http://localhost:3000; then
-              echo "Server is ready!"
-              exit 0
-            fi
+            curl --silent --fail http://localhost:3000 && break
             echo "Waiting for server to be ready..."
             sleep 5
-          done
-          echo "Server failed to start!"
-          exit 1
+          done || (echo "Server failed to start!" && exit 1)
 
       - name: Install Meticulous CLI
         run: |
-          yarn add @alwaysmeticulous/cli
-          echo "./node_modules/.bin" >> $GITHUB_PATH
+          yarn global add @alwaysmeticulous/cli
+          echo "$(yarn global bin)" >> $GITHUB_PATH
 
-            - name: Run Meticulous Visual Tests
+      - name: Run Meticulous Visual Tests
         run: |
           if [ -z "${{ secrets.METICULOUS_API_TOKEN }}" ]; then
             echo "Error: METICULOUS_API_TOKEN is not set. Exiting."
