Test change to trigger Meticulous

diff --git a/.github/workflows/sample-app-web.yml b/.github/workflows/sample-app-web.yml
--- a/.github/workflows/sample-app-web.yml
+++ b/.github/workflows/sample-app-web.yml
@@ -2,9 +2,13 @@ on:
   push:
     branches:
       - main
-      - baseline-branch 
-      - new-visual-branch # Add baseline-branch if you need to trigger for that branch too
-  pull_request: {}
+      - baseline-branch
+      - new-visual-branch
+  pull_request:
+    branches:
+      - main
+      - baseline-branch
+      - new-visual-branch
   workflow_dispatch: {}
 
 permissions:
@@ -52,15 +56,20 @@ jobs:
       - name: Start server in background
         run: |
           yarn global add serve
-          serve -s build -l 3000 & echo $! > server.pid
+          nohup serve -s build -l 3000 & echo $! > server.pid
 
       - name: Wait for server to be ready
         run: |
           for i in {1..12}; do  
-            curl --silent --fail http://localhost:3000 && break
+            if curl --silent --fail http://localhost:3000; then
+              echo "Server is ready!"
+              exit 0
+            fi
             echo "Waiting for server to be ready..."
             sleep 5
-          done || (echo "Server failed to start!" && exit 1)
+          done
+          echo "Server failed to start!"
+          exit 1
 
       - name: Install Meticulous CLI
         run: |
@@ -68,13 +77,19 @@ jobs:
           echo "$(yarn global bin)" >> $GITHUB_PATH
 
       - name: Run Meticulous Visual Tests
+        env:
+          METICULOUS_API_TOKEN: ${{ secrets.METICULOUS_API_TOKEN }}
         run: |
+          if [ -z "$METICULOUS_API_TOKEN" ]; then
+            echo "Error: Meticulous API token is missing!"
+            exit 1
+          fi
           meticulous run-all-tests \
             --apiToken=${{ secrets.METICULOUS_API_TOKEN }} \
             --appUrl="http://localhost:3000/" \
             --headless \
-            --noSandbox \
-            --baseTestRunId=Pkm7WCBcGMRzfgtTd7Mdc8rNNt
+            --noSandbox
+
       - name: Stop server
         run: |
           kill $(cat server.pid) || true
